### ISSUE TITLE
Figure out unique identifier for stars

### ISSUE THREAD

**Issue by kstoreyf** [panoptes/PIAA#6]
based on canonical RA and Dec? will be used to combine all light curves from the same star and included in PSC headers and light curve metadata

**Comment by wtgee** [comment]
@joshwalawender @oguyon We are using a set catalog for the initial list of stars, correct? Should we use the actual catalog name or standardize on RA/Dec?

**Comment by joshwalawender** [comment]
I propose that we start by simply selecting stars in an existing catalog which we also reliably detect in our images.  We should designate them using RA and Dec, but the designation is then immutable even if the coordinates change via precession, proper motion, etc.  The measured star position will often not precisely match the catalog coordinates due to measurement error, so we need to begin with some fiducial coordinate.

In an analogy to the Kepler Input Catalog, I think we should call it the PANOPTES Input Catalog.  Stars would then be `PIC JHHMMSS.SS+DDMMSS.S`.  We could literally clone the JHHMMSS.SS+DDMMSS.S part of the designation from 2MASS or some other catalog.

We can always expand the PIC catalog later to include an order of magnitude more stars if we wanted to, but I say start small with fewer stars and expand later.  Get PIAA working on fewer KIC stars which are best case examples, then make it work on a bigger input set with more difficult cases (e.g. stars which are blended with other stars, etc.).

**Comment by wtgee** [comment]
@joshwalawender Sounds good. Is it standard naming for the catalogs to use the Ra/Dec? I thought the KIC was just sequential but never really looked into.

**Comment by joshwalawender** [comment]
If I recall correctly, KOI is sequential, but I don't know about KIC.  Since we're all over the sky and Kepler (K1 at least) wasn't, I think we should adopt the coordinate based ID.  I'm generally annoyed by these long phone number names in catalogs and grumble when I have to use them in papers, but I don't have a better idea and it seems to be a relatively common standard (see point source catalogs for 2MASS, WISE, Spitzer, SDSS, etc.).  I'm open to other ideas.  

If we already had a detailed plan for which fields we would observe, we could come up with a naming scheme which used the field and then some sort of sequential ID for stars within the field, but I don't think we're ready to commit to fields yet.

**Comment by wtgee** [comment]
@joshwalawender Sounds good to me. We also need a unique field id. Separate Issue I suppose unless that's already set somehow.

**Comment by joshwalawender** [comment]
Yeah, that is separate.  It is more important for the scheduler than for the analysis.  If PIAA is only handed PSCs from a sequence on `field_a`, then it doesn't care if `PIC J010203.04+050607.8` was observed as part of `field_a` one night and is part of `field_b` on another night.  The light curves from each of those are combined in the cloud later on.

**Comment by kstoreyf** [comment]
should this ID be part of the metadata of the PSC and light curve (that are output by the on-unit analysis and input into the light curve combination/analysis algorithm)? aka, should there be a "PICID" field in https://github.com/panoptes/PIAA/wiki/Metadata-for-Images-and-Postage-Stamp-Cubes ?

**Comment by joshwalawender** [comment]
Yes.  It looks like it is already listed under the metadata for the PSC.

**Comment by oguyon** [comment]
I agree with this naming strategy
We can build/provide conversion tables between our own catalog and other 
catalogs as needed, over time
